"""added date field

Revision ID: e3351549a1ef
Revises: 7e7d906a40e0
Create Date: 2020-10-29 21:57:18.347124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3351549a1ef'
down_revision = '7e7d906a40e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('posted_on', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'posted_on')
    # ### end Alembic commands ###
