version: "3"

services:
  app:
    build:
      context: ../
      dockerfile: docker/app.dockerfile
    image: app_testing
    command: bash docker/entrypoint.sh migrate
    ports:
      - "8000:8000"
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://postgres@postgres:5432/main"
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  test:
    build:
      context: ../
      dockerfile: docker/test.dockerfile
    image: test_env
    command: bash -c "sleep 7 && python -m tests.conftest && pytest tests/"
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://postgres@postgres:5432/main"
      HOST: "http://app:8000"
    depends_on:
      - postgres
      - app
